In [1]:
import csv
import random
import math
import numpy as np
import pandas as pd

from pandas import read_csv

In [18]:
f18 = read_csv("DemocracyFeb2018.csv", index_col=0)
f18tot = f18.iloc[1:,1]
f18pos = f18.iloc[1:,2]
f18neg = f18.iloc[1:,3]
f19 = read_csv("DemocracyFeb2019.csv", index_col=0)
f19tot = f19.iloc[1:,1]
f19pos = f19.iloc[1:,2]
f19neg = f19.iloc[1:,3]
f20 = read_csv("DemocracyFeb2020.csv", index_col=0)
f20tot = f20.iloc[2:,1]
f20pos = f20.iloc[2:,2]
f20neg = f20.iloc[2:,3]
f21 = read_csv("DemocracyFeb2021.csv", index_col=0)
f21tot = f21.iloc[:,1]
f21pos = f21.iloc[:,2]
f21neg = f21.iloc[:,3]
f22 = read_csv("DemocracyFeb2022.csv", index_col=0)
f22tot = f22.iloc[1:,1]
f22pos = f22.iloc[1:,2]
f22neg = f22.iloc[1:,3]

m18 = read_csv("DemocracyMarch2018.csv", index_col=0)
print(m18.shape)
m18tot = m18.iloc[:,1]
m18pos = m18.iloc[:,2]
m18neg = m18.iloc[:,3]
m19 = read_csv("DemocracyMarch2019.csv", index_col=0)
print(m19.shape)
m19tot = m19.iloc[:,1]
m19pos = m19.iloc[:,2]
m19neg = m19.iloc[:,3]
m20 = read_csv("DemocracyMarch2020.csv", index_col=0)
print(m20.shape)
m20tot = m20.iloc[:,1]
m20pos = m20.iloc[:,2]
m20neg = m20.iloc[:,3]
m21 = read_csv("DemocracyMarch2021.csv", index_col=0)
print(m21.shape)
m21tot = m21.iloc[:,1]
m21pos = m21.iloc[:,2]
m21neg = m21.iloc[:,3]
m22 = read_csv("DemocracyMarch2022.csv", index_col=0)
print(m22.shape)
m22tot = m22.iloc[:,1]
m22pos = m22.iloc[:,2]
m22neg = m22.iloc[:,3]

(31, 4)
(31, 4)
(31, 4)
(31, 4)
(31, 4)


In [26]:
febTots = {0:f18tot, 1:f19tot, 2:f20tot, 3:f21tot, 4:f22tot}
febPos = {0:f18pos, 1:f19pos, 2:f20pos, 3:f21pos, 4:f22pos}
febNeg = {0:f18neg, 1:f19neg, 2:f20neg, 3:f21neg, 4:f22neg}

febCorrTots = np.ones((5,5))
for i in range(5):
    for j in range(5):
        a = febTots[i]
        b = febTots[j]
        febCorrTots[i,j] = abs((np.corrcoef(a, b))[1,0])
        
print("FEBRUARY")
print("Totals:")        
print(febCorrTots)


febCorrPos = np.ones((5,5))
for i in range(5):
    for j in range(5):
        a = febPos[i]
        b = febPos[j]
        febCorrPos[i,j] = abs((np.corrcoef(a, b))[1,0])

print("Positives: ")
print(febCorrPos)


febCorrNeg = np.ones((5,5))
for i in range(5):
    for j in range(5):
        a = febNeg[i]
        b = febNeg[j]
        febCorrNeg[i,j] = abs((np.corrcoef(a, b))[1,0])

print("Negatives: ")        
print(febCorrNeg)
print(" ")
print(" ")
avgCorrTots = np.ones((1,5))
for i in range(5):
    sum = 0
    for j in range(5):
        sum += febCorrTots[i, j]
    avgCorrTots[0,i] = sum / 5
    
print("Total Averages")    
print(avgCorrTots)
print(" ")

avgCorrTots = np.ones((1,5))
for i in range(5):
    sum = 0
    for j in range(5):
        sum += febCorrPos[i, j]
    avgCorrTots[0,i] = sum / 5
    
print("Positive Averages")    
print(avgCorrTots)
print(" ")

avgCorrTots = np.ones((1,5))
for i in range(5):
    sum = 0
    for j in range(5):
        sum += febCorrNeg[i, j]
    avgCorrTots[0,i] = sum / 5
    
print("Positive Averages")    
print(avgCorrTots)

FEBRUARY
Totals:
[[1.         0.22533455 0.16908162 0.06097507 0.03899181]
 [0.22533455 1.         0.11624394 0.0958885  0.3831999 ]
 [0.16908162 0.11624394 1.         0.38153203 0.23483536]
 [0.06097507 0.0958885  0.38153203 1.         0.30645536]
 [0.03899181 0.3831999  0.23483536 0.30645536 1.        ]]
Positives: 
[[1.         0.25233103 0.17426943 0.11043279 0.1108268 ]
 [0.25233103 1.         0.21742536 0.08776487 0.07352754]
 [0.17426943 0.21742536 1.         0.24188112 0.16207258]
 [0.11043279 0.08776487 0.24188112 1.         0.07219655]
 [0.1108268  0.07352754 0.16207258 0.07219655 1.        ]]
Negatives: 
[[1.         0.18914532 0.05874983 0.11464815 0.0780033 ]
 [0.18914532 1.         0.21742536 0.08776487 0.07352754]
 [0.05874983 0.21742536 1.         0.24188112 0.16207258]
 [0.11464815 0.08776487 0.24188112 1.         0.07219655]
 [0.0780033  0.07352754 0.16207258 0.07219655 1.        ]]
 
 
Total Averages
[[0.29887661 0.36413338 0.38033859 0.36897019 0.39269649]]
 
Positi

In [28]:
marTots = {0:m18tot, 1:m19tot, 2:m20tot, 3:m21tot, 4:m22tot}
marPos = {0:m18pos, 1:m19pos, 2:m20pos, 3:m21pos, 4:m22pos}
marNeg = {0:m18neg, 1:m19neg, 2:m20neg, 3:m21neg, 4:m22neg}
print("MARCH")
marCorrTots = np.ones((5,5))
for i in range(5):
    for j in range(5):
        a = marTots[i]
        b = marTots[j]
        marCorrTots[i,j] = abs((np.corrcoef(a, b))[1,0])
print("Totals:")        
print(marCorrTots)


marCorrPos = np.ones((5,5))
for i in range(5):
    for j in range(5):
        a = marPos[i]
        b = marPos[j]
        marCorrPos[i,j] = abs((np.corrcoef(a, b))[1,0])

print("Positives: ")
print(marCorrPos)


marCorrNeg = np.ones((5,5))
for i in range(5):
    for j in range(5):
        a = marNeg[i]
        b = marNeg[j]
        marCorrNeg[i,j] = abs((np.corrcoef(a, b))[1,0])

print("Negatives: ")        
print(marCorrNeg)

print(" ")
print(" ")
avgCorrTots = np.ones((1,5))
for i in range(5):
    sum = 0
    for j in range(5):
        sum += marCorrTots[i, j]
    avgCorrTots[0,i] = sum / 5
    
print("Total Averages")    
print(avgCorrTots)
print(" ")

avgCorrTots = np.ones((1,5))
for i in range(5):
    sum = 0
    for j in range(5):
        sum += marCorrPos[i, j]
    avgCorrTots[0,i] = sum / 5
    
print("Positive Averages")    
print(avgCorrTots)
print(" ")

avgCorrTots = np.ones((1,5))
for i in range(5):
    sum = 0
    for j in range(5):
        sum += marCorrNeg[i, j]
    avgCorrTots[0,i] = sum / 5
    
print("Positive Averages")    
print(avgCorrTots)

MARCH
Totals:
[[1.         0.05325158 0.07595482 0.09022659 0.13439658]
 [0.05325158 1.         0.43536688 0.18993099 0.29187471]
 [0.07595482 0.43536688 1.         0.2383682  0.04904017]
 [0.09022659 0.18993099 0.2383682  1.         0.22577531]
 [0.13439658 0.29187471 0.04904017 0.22577531 1.        ]]
Positives: 
[[1.         0.16432366 0.03323714 0.05008119 0.01667178]
 [0.16432366 1.         0.07518646 0.04002844 0.26933002]
 [0.03323714 0.07518646 1.         0.13571556 0.03322068]
 [0.05008119 0.04002844 0.13571556 1.         0.0893605 ]
 [0.01667178 0.26933002 0.03322068 0.0893605  1.        ]]
Negatives: 
[[1.         0.10384811 0.24184245 0.18754881 0.10837899]
 [0.10384811 1.         0.07518646 0.31416093 0.26933002]
 [0.24184245 0.07518646 1.         0.09550872 0.03322068]
 [0.18754881 0.31416093 0.09550872 1.         0.05776274]
 [0.10837899 0.26933002 0.03322068 0.05776274 1.        ]]
 
 
Total Averages
[[0.27076592 0.39408483 0.35974601 0.34886022 0.34021735]]
 
Positive 